### ISSUE TITLE
peer implementations should expose Base.Link

### ISSUE THREAD

**Issue by robertkowalski** [bitfinexcom/grenache-nodejs-ws#11]
It would come handy if each peer implementation would expose the `Link` constructor function.

Then I could do something like:

```js
const Grenache = require('grenache-nodejs-ws')

const link = new Grenache.Link({
  grape: 'ws://127.0.0.1:30001'
})
link.start()

const peer = new Grenache.Peer(link, {})
peer.init()
```

This would make general usage easier and it would help us for writing easy understandable API docs and tutorials. In general it hides a bit of the implementation details and makes the usage more user friendly. Its also easy to do, as all Peer implementations built upon Base anyway.

**Comment by prdn** [comment]
@robertkowalski I agree.
Can you make the change?

**Comment by robertkowalski** [comment]
yep!
