### ISSUE TITLE
NPM package is outdated with same version number

### ISSUE THREAD

**Issue by RichAyotte** [bitfinexcom/grenache-nodejs-ws#30]
During the uws -> ws transition, it looks like the package was either not published to NPM or the version wasn't bumped.

For instance here's what TransportPub.js currently looks like on NPM.
```
'use strict'

const uuid = require('uuid')
const UWS = require('uws')
const Base = require('grenache-nodejs-base')
const assert = require('assert')

class TransportPub extends Base.TransportPub {
  init () {
    super.init()

    this._sockets = new Map()
  }

  listen (port) {
    assert(Number.isInteger(port), 'port must be an Integer')

    this.listening()

    const socket = new UWS.Server({ port: port })
...
```

**Comment by RichAyotte** [comment]
I forgot to mention, the uws package is no longer on NPM which breaks this package.

https://www.npmjs.com/package/uws

**Comment by parweb** [comment]
maybe replace by https://www.npmjs.com/package/ws ?!

**Comment by robertkowalski** [comment]
This was fixed in October:

https://github.com/bitfinexcom/grenache-nodejs-ws/pull/29/commits/44f5ce0ca13e316bd821854cf7e96cac9cfa0833

**Comment by RichAyotte** [comment]
Yes but the fix didn't make it to NPM for some reason. Was it published?

**Comment by robertkowalski** [comment]
no it was not published yet.

for now you would have to use it as git dependency.

**Comment by RichAyotte** [comment]
I understand how to use this package outside of npm, that's not what I was reporting. I was just reporting that the published NPM packages was broken and contained the same version as master.
